/*
 * Yagna Activity API
 *
 * It conforms with capability level 1 of the [Activity API specification](https://golem-network.gitbook.io/golem-internal-documentation-test/golem-activity-protocol/golem-activity-api).
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(thiserror::Error, Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
#[error("Yagna API error: {message:?}")]
pub struct ErrorMessage {
    pub message: Option<String>,
}

impl ErrorMessage {
    pub fn new(message: impl ToString) -> ErrorMessage {
        ErrorMessage {
            message: Some(message.to_string()),
        }
    }
}

impl<T: Into<String>> From<T> for ErrorMessage {
    fn from(s: T) -> Self {
        Self::new(s.into())
    }
}
