/*
 * Yagna Market API
 *
 * The version of the OpenAPI document: 1.6.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// Generic Event reason information structure.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Reason {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl Reason {
    /// Generic Event reason information structure.
    pub fn new() -> Reason {
        Reason { message: None }
    }
}
