name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - release/*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    env:
      RUSTFLAGS: "-D warnings -C opt-level=z -C target-cpu=native -C debuginfo=1"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up mise
        uses: jdx/mise-action@v4.2.5

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target1-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo fmt
        run: mise x -- cargo fmt --all -- --check

      - name: cargo test
        run: mise x -- cargo test --workspace

      - name: cargo test with Diesel integration
        run: mise x -- cargo test -p ya-client-model --features with-diesel

      - name: cargo test cli
        run: mise x -- cargo test --features cli

      - name: cargo build
        run: mise x -- cargo build --workspace
